/*
* Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.applicant.domain.repo;



import ht.bms.applicant.domain.BmsCodegen;
import ht.bms.applicant.domain.BmsRole;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;
import java.util.Optional;


/**
 * Spring JPA Repository for BmsCodegen
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BmsCogeGenRepository extends CrudRepository<BmsCodegen, String> {

}