/*
 * Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.applicant.domain.repo;


import ht.bms.applicant.domain.BmsOffice;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;
import java.util.Optional;

/**
 * Spring JPA Repository for BmsOffice
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BmsOfficeRepository extends CrudRepository<BmsOffice, BigDecimal> , JpaSpecificationExecutor<BmsOffice> {
	
	@Query("select off from BmsOffice off where off.isCentral = ?1 and off.institutionId = ?2")
	public Optional<BmsOffice> getBmsOfficeCentral(BigDecimal isCentral,BigDecimal institutionId);
	
	@Query("select off from BmsOffice off where off.institutionId = ?1")
	public Optional<BmsOffice> getBmsOfficeInstitutionId(BigDecimal institutionId);

}