/*
 * Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.applicant.domain.repo;


import ht.bms.applicant.domain.BmsTx;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Optional;


public interface BmsTxRepository extends CrudRepository<BmsTx,BigDecimal>,PagingAndSortingRepository<BmsTx,BigDecimal>, JpaSpecificationExecutor<BmsTx> {
	
//	public BmsTx getBmsTxByTxCode(String Txode);
	

	
/*	@Query(value = "SELECT * FROM bms_tx t where t.user_tranction =:userId  and is_current=0  order by t.tx_date desc", nativeQuery = true)
	public List<BmsTx>findActiveTxByUserId(BigDecimal userId);*/
	
	
	@Query("select t.txId from BmsTx t where t.userId = ?1 AND t.isCurrent=0")
	public BigDecimal checkCurrentTransactionId(BigDecimal userId);
	
/*	@Query("select t.txId from BmsTx t where t.bmsCalendar.dateStr =?1")
	public Optional<BmsTx> exit(String date);*/

	
	@Query("select t.txId from BmsTx t  where t.txId = ?1   AND  t.bmsTxStatus.statusId>=1  AND  t.bmsTxType.id>=25 AND   t.isCurrent=0")
	public BigDecimal checkFormIsSubmitAndSign(BigDecimal txId);
	
	@Query("select t from BmsTx t  "
			+ "where t.txId = ?1 AND"
			+ " t.bmsTxStatus.statusId =?2 AND"
			+ " t.bmsTxType.id =?3 AND"
			+ "  t.isCurrent=0")
	public Optional<BmsTx> checkApplicantFormStepByTxId(BigDecimal txId,BigDecimal status,BigDecimal type);
	

	
	
/*	@Query("select count(tx.txId) from BmsTx tx join"
			+ " tx.bmsCalendar txCal join"
			+ " tx.bmsOffice txOffice join"
			+ " tx.bmsService txService "
			+ "where txCal.dateStr = ?1 and txOffice.officeId = ?2 and txService.osId = ?3 and tx.bmsTxType.id=26")
	public int checkNumberTransaction_PAY_For_Office_For_Service_BY_Date(String txDate, BigDecimal officeId,BigDecimal serviceId);
	
	*/
	
	@Query("update BmsTx b set "
			+ "b.updatedDate = ?1, "
			+ "b.bmsTxStatus.statusId = ?2, "
			+ "b.bmsTxType.id = ?3  "
			+ "where b.txId = ?4")
	public void updateBmsTx(Timestamp updateDate,long status, long type,BigDecimal txId);
	
	@Query("update BmsTx b set "
			+ "b.isCurrent = ?1 "
			+ "where b.txId = ?2")
	public void setIsCurrentTx(long isCurrent,BigDecimal txId);
	
	
	
	
	

	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxStatus.statusId >11")
	public long countAll();
	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxType.id =31")
	public long countTraitment();
	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxType.id =28")
	public long countApproved();
	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxType.id =29")
	public long countReject();
	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxType.id =32")
	public long countDelivery();
	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxType.id <=25")
	public long countDemandeIncomplete();
	
	@Query("select count(t.txId) from BmsTx t  where  t.bmsTxType.id >=26")
	public long countDemandeSubmit();
	
	
	
	
}


